spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:127.0.0.1:5432}/sso
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
mybatis:
  configuration:
    map-underscore-to-camel-case: false
